// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class weex : Exchange
{
    public weex (object args = null): base(args) {}

    public async Task<object> publicGetPublicTime (object parameters = null)
    {
        return await this.callAsync ("publicGetPublicTime",parameters);
    }

    public async Task<object> publicGetPublicCurrencies (object parameters = null)
    {
        return await this.callAsync ("publicGetPublicCurrencies",parameters);
    }

    public async Task<object> publicGetPublicProducts (object parameters = null)
    {
        return await this.callAsync ("publicGetPublicProducts",parameters);
    }

    public async Task<object> publicGetPublicExchangeInfo (object parameters = null)
    {
        return await this.callAsync ("publicGetPublicExchangeInfo",parameters);
    }

    public async Task<object> publicGetMarketTicker (object parameters = null)
    {
        return await this.callAsync ("publicGetMarketTicker",parameters);
    }

    public async Task<object> publicGetMarketTickers (object parameters = null)
    {
        return await this.callAsync ("publicGetMarketTickers",parameters);
    }

    public async Task<object> publicGetMarketFills (object parameters = null)
    {
        return await this.callAsync ("publicGetMarketFills",parameters);
    }

    public async Task<object> publicGetMarketCandles (object parameters = null)
    {
        return await this.callAsync ("publicGetMarketCandles",parameters);
    }

    public async Task<object> publicGetMarketDepth (object parameters = null)
    {
        return await this.callAsync ("publicGetMarketDepth",parameters);
    }

    public async Task<object> privateGetAccountAssets (object parameters = null)
    {
        return await this.callAsync ("privateGetAccountAssets",parameters);
    }

    public async Task<object> privateGetAccountTransferRecords (object parameters = null)
    {
        return await this.callAsync ("privateGetAccountTransferRecords",parameters);
    }

    public async Task<object> privatePostAccountBills (object parameters = null)
    {
        return await this.callAsync ("privatePostAccountBills",parameters);
    }

    public async Task<object> privatePostTradeOrders (object parameters = null)
    {
        return await this.callAsync ("privatePostTradeOrders",parameters);
    }

    public async Task<object> privatePostTradeBatchOrders (object parameters = null)
    {
        return await this.callAsync ("privatePostTradeBatchOrders",parameters);
    }

    public async Task<object> privatePostTradeCancelOrder (object parameters = null)
    {
        return await this.callAsync ("privatePostTradeCancelOrder",parameters);
    }

    public async Task<object> privatePostTradeCancelBatchOrders (object parameters = null)
    {
        return await this.callAsync ("privatePostTradeCancelBatchOrders",parameters);
    }

    public async Task<object> privatePostTradeCancelSymbolOrder (object parameters = null)
    {
        return await this.callAsync ("privatePostTradeCancelSymbolOrder",parameters);
    }

    public async Task<object> privatePostTradeOrderInfo (object parameters = null)
    {
        return await this.callAsync ("privatePostTradeOrderInfo",parameters);
    }

    public async Task<object> privatePostTradeOpenOrders (object parameters = null)
    {
        return await this.callAsync ("privatePostTradeOpenOrders",parameters);
    }

    public async Task<object> privatePostTradeHistory (object parameters = null)
    {
        return await this.callAsync ("privatePostTradeHistory",parameters);
    }

    public async Task<object> privatePostTradeFills (object parameters = null)
    {
        return await this.callAsync ("privatePostTradeFills",parameters);
    }

}