package ccxt

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

type weex struct {
    Exchange

}

func NewWeexCore() weex {
   p := weex{}
   setDefaults(&p)
   return p
}

func  (this *weex) Describe() interface{}  {
    return this.DeepExtend(this.Exchange.Describe(), map[string]interface{} {
        "id": "weex",
        "name": "WEEX",
        "countries": []interface{}{"SC"},
        "rateLimit": 100,
        "version": "v2",
        "certified": false,
        "pro": true,
        "has": map[string]interface{} {
            "CORS": nil,
            "spot": true,
            "margin": false,
            "swap": false,
            "future": false,
            "option": false,
            "addMargin": false,
            "borrowCrossMargin": false,
            "borrowIsolatedMargin": false,
            "cancelAllOrders": true,
            "cancelOrder": true,
            "cancelOrders": true,
            "closeAllPositions": false,
            "closePosition": false,
            "createDepositAddress": false,
            "createLimitBuyOrder": true,
            "createLimitSellOrder": true,
            "createMarketBuyOrder": true,
            "createMarketOrderWithCost": true,
            "createMarketSellOrder": true,
            "createOrder": true,
            "createOrders": true,
            "createOrderWithTakeProfitAndStopLoss": false,
            "createPostOnlyOrder": true,
            "createReduceOnlyOrder": false,
            "createStopLimitOrder": false,
            "createStopLossOrder": false,
            "createStopMarketOrder": false,
            "createStopOrder": false,
            "createTakeProfitOrder": false,
            "createTrailingPercentOrder": false,
            "createTriggerOrder": false,
            "editOrder": false,
            "fetchBalance": true,
            "fetchBidsAsks": false,
            "fetchBorrowInterest": false,
            "fetchBorrowRateHistories": false,
            "fetchBorrowRateHistory": false,
            "fetchClosedOrders": false,
            "fetchCurrencies": true,
            "fetchDepositAddress": false,
            "fetchDepositAddresses": false,
            "fetchDeposits": false,
            "fetchFundingHistory": false,
            "fetchFundingRate": false,
            "fetchFundingRateHistory": false,
            "fetchFundingRates": false,
            "fetchIndexOHLCV": false,
            "fetchL2OrderBook": false,
            "fetchLastPrices": false,
            "fetchLedger": true,
            "fetchMarkets": true,
            "fetchMyTrades": true,
            "fetchOHLCV": true,
            "fetchOpenInterest": false,
            "fetchOpenInterestHistory": false,
            "fetchOpenOrders": true,
            "fetchOrder": true,
            "fetchOrderBook": true,
            "fetchOrders": true,
            "fetchOrderTrades": false,
            "fetchPosition": false,
            "fetchPositions": false,
            "fetchPositionsRisk": false,
            "fetchPremiumIndexOHLCV": false,
            "fetchStatus": true,
            "fetchTicker": true,
            "fetchTickers": true,
            "fetchTime": true,
            "fetchTrades": true,
            "fetchTradingFee": false,
            "fetchTradingFees": false,
            "fetchTransfers": true,
            "fetchWithdrawals": false,
            "reduceMargin": false,
            "setLeverage": false,
            "setMarginMode": false,
            "setPositionMode": false,
            "transfer": false,
            "withdraw": false,
        },
        "timeframes": map[string]interface{} {
            "1m": "1m",
            "5m": "5m",
            "15m": "15m",
            "30m": "30m",
            "1h": "1h",
            "2h": "2h",
            "4h": "4h",
            "6h": "6h",
            "8h": "8h",
            "12h": "12h",
            "1d": "1day",
            "1w": "1week",
            "1M": "1M",
        },
        "urls": map[string]interface{} {
            "logo": "https://user-images.githubusercontent.com/1294454/85734211-85755480-b705-11ea-8b35-0b7f1db33a2f.jpg",
            "api": map[string]interface{} {
                "public": "https://api-spot.weex.com/api/v2",
                "private": "https://api-spot.weex.com/api/v2",
            },
            "www": "https://www.weex.com",
            "doc": []interface{}{"https://doc-en.weex.com", "https://github.com/weex-exchange"},
            "fees": "https://www.weex.com/fees",
            "referral": nil,
        },
        "api": map[string]interface{} {
            "public": map[string]interface{} {
                "get": map[string]interface{} {
                    "public/time": 1,
                    "public/currencies": 1,
                    "public/products": 1,
                    "public/exchangeInfo": 1,
                    "market/ticker": 1,
                    "market/tickers": 1,
                    "market/fills": 1,
                    "market/candles": 1,
                    "market/depth": 1,
                },
            },
            "private": map[string]interface{} {
                "get": map[string]interface{} {
                    "account/assets": 1,
                    "account/transferRecords": 1,
                },
                "post": map[string]interface{} {
                    "account/bills": 1,
                    "trade/orders": 1,
                    "trade/batch-orders": 1,
                    "trade/cancel-order": 1,
                    "trade/cancel-batch-orders": 1,
                    "trade/cancel-symbol-order": 1,
                    "trade/orderInfo": 1,
                    "trade/open-orders": 1,
                    "trade/history": 1,
                    "trade/fills": 1,
                },
            },
        },
        "fees": map[string]interface{} {
            "trading": map[string]interface{} {
                "tierBased": false,
                "percentage": true,
                "maker": this.ParseNumber("0.001"),
                "taker": this.ParseNumber("0.001"),
            },
        },
        "precisionMode": TICK_SIZE,
        "exceptions": map[string]interface{} {
            "exact": map[string]interface{} {
                "40001": AuthenticationError,
                "40002": AuthenticationError,
                "40003": AuthenticationError,
                "40005": InvalidNonce,
                "40006": AuthenticationError,
                "40007": BadRequest,
                "40008": InvalidNonce,
                "40009": AuthenticationError,
                "40011": AuthenticationError,
                "40012": AuthenticationError,
                "40013": AccountSuspended,
                "40014": PermissionDenied,
                "40015": ExchangeError,
                "40017": BadRequest,
                "40018": PermissionDenied,
                "40102": BadSymbol,
                "40200": OnMaintenance,
                "40305": InvalidOrder,
                "40409": BadRequest,
                "40704": BadRequest,
                "40707": BadRequest,
                "40724": BadRequest,
                "40725": BadRequest,
                "40912": BadRequest,
                "40913": ArgumentsRequired,
                "43001": OrderNotFound,
                "43002": InvalidOrder,
                "43004": OrderNotFound,
                "43005": InvalidOrder,
                "43006": InvalidOrder,
                "43007": InvalidOrder,
                "43009": InvalidOrder,
                "43010": InvalidOrder,
                "43011": InvalidOrder,
                "429": RateLimitExceeded,
            },
            "broad": map[string]interface{} {},
        },
        "commonCurrencies": map[string]interface{} {},
    })
}
func  (this *weex) FetchTime(optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    /**
            * @method
            * @name weex#fetchTime
            * @description fetches the current integer timestamp in milliseconds from the exchange server
            * @see https://doc-en.weex.com/#get-server-time
            * @param {object} [params] extra parameters specific to the exchange API endpoint
            * @returns {int} the current integer timestamp in milliseconds from the exchange server
            */
            params := GetArg(optionalArgs, 0, map[string]interface{} {})
            _ = params
        
            response:= (<-this.PublicGetPublicTime(params))
            PanicOnError(response)
        
                //
            //     {
            //         "code": "00000",
            //         "msg": "success",
            //         "requestTime": 1622097118135,
            //         "data": 1622097118134
            //     }
            //
        ch <- this.SafeInteger(response, "data")
            return nil
        
            }()
            return ch
        }
func  (this *weex) FetchCurrencies(optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    /**
            * @method
            * @name weex#fetchCurrencies
            * @description fetches all available currencies on an exchange
            * @see https://doc-en.weex.com/#basic-crypto-information
            * @param {object} [params] extra parameters specific to the exchange API endpoint
            * @returns {object} an associative dictionary of currencies
            */
            params := GetArg(optionalArgs, 0, map[string]interface{} {})
            _ = params
        
            response:= (<-this.PublicGetPublicCurrencies(params))
            PanicOnError(response)
            //
            //     {
            //         "code":"00000",
            //         "msg":"success",
            //         "requestTime":1622097139437,
            //         "data":[
            //             {
            //                 "coinId":"1",
            //                 "coinName":"BTC",
            //                 "transfer":"true",
            //                 "chains":[
            //                     {
            //                         "chain":null,
            //                         "needTag":"false",
            //                         "withdrawAble":"true",
            //                         "rechargeAble":"true",
            //                         "withdrawFee":"0.005",
            //                         "depositConfirm":"1",
            //                         "withdrawConfirm":"1",
            //                         "minDepositAmount":"0.001",
            //                         "minWithdrawAmount":"0.001",
            //                         "browserUrl":"https://blockchair.com/bitcoin/testnet/transaction/"
            //                     }
            //                 ]
            //             }
            //         ]
            //     }
            //
            var data interface{} = this.SafeList(response, "data", []interface{}{})
            var result interface{} = map[string]interface{} {}
            for i := 0; IsLessThan(i, GetArrayLength(data)); i++ {
                var currency interface{} = GetValue(data, i)
                var id interface{} = this.SafeString(currency, "coinName")
                var code interface{} = this.SafeCurrencyCode(id)
                var chains interface{} = this.SafeList(currency, "chains", []interface{}{})
                var networks interface{} = map[string]interface{} {}
                var fee interface{} = nil
                for j := 0; IsLessThan(j, GetArrayLength(chains)); j++ {
                    var chain interface{} = GetValue(chains, j)
                    var networkId interface{} = this.SafeString(chain, "chain")
                    var networkCode interface{} = Ternary(IsTrue(networkId), networkId, id)
                    var withdrawEnabled interface{} = this.SafeBool(chain, "withdrawAble")
                    var depositEnabled interface{} = this.SafeBool(chain, "rechargeAble")
                    var withdrawFee interface{} = this.SafeNumber(chain, "withdrawFee")
                    if IsTrue(IsEqual(fee, nil)) {
                        fee = withdrawFee
                    }
                    AddElementToObject(networks, networkCode, map[string]interface{} {
            "info": chain,
            "id": networkId,
            "network": networkCode,
            "active": IsTrue(withdrawEnabled) && IsTrue(depositEnabled),
            "deposit": depositEnabled,
            "withdraw": withdrawEnabled,
            "fee": withdrawFee,
            "precision": nil,
            "limits": map[string]interface{} {
                "withdraw": map[string]interface{} {
                    "min": this.SafeNumber(chain, "minWithdrawAmount"),
                    "max": nil,
                },
                "deposit": map[string]interface{} {
                    "min": this.SafeNumber(chain, "minDepositAmount"),
                    "max": nil,
                },
            },
        })
                }
                AddElementToObject(result, code, map[string]interface{} {
            "info": currency,
            "id": id,
            "numericId": this.SafeString(currency, "coinId"),
            "code": code,
            "precision": nil,
            "type": nil,
            "name": nil,
            "active": nil,
            "deposit": nil,
            "withdraw": nil,
            "networks": networks,
            "fee": fee,
            "limits": map[string]interface{} {
                "amount": map[string]interface{} {
                    "min": nil,
                    "max": nil,
                },
            },
        })
            }
        
            ch <- result
            return nil
        
            }()
            return ch
        }
func  (this *weex) FetchMarkets(optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    /**
            * @method
            * @name weex#fetchMarkets
            * @description retrieves data on all markets for weex
            * @see https://doc-en.weex.com/#get-symbol-info
            * @param {object} [params] extra parameters specific to the exchange API endpoint
            * @returns {object[]} an array of objects representing market data
            */
            params := GetArg(optionalArgs, 0, map[string]interface{} {})
            _ = params
        
            response:= (<-this.PublicGetPublicExchangeInfo(params))
            PanicOnError(response)
            //
            //     {
            //       "code": "00000",
            //       "msg": "success",
            //       "requestTime": 1743661516052,
            //       "data": [
            //         {
            //           "symbol": "BTCUSDT_SPBL",
            //           "baseCoin": "BTC",
            //           "quoteCoin": "USDT",
            //           "tickSize": "0.1",
            //           "stepSize": "0.00000001",
            //           "minTradeAmount": "0.00001",
            //           "maxTradeAmount": "99999",
            //           "takerFeeRate": "0.001",
            //           "makerFeeRate": "0",
            //           "enableTrade": true,
            //           "enableDisplay": true
            //         }
            //       ]
            //     }
            //
            var data interface{} = this.SafeList(response, "data", []interface{}{})
            var result interface{} = []interface{}{}
            for i := 0; IsLessThan(i, GetArrayLength(data)); i++ {
                var market interface{} = GetValue(data, i)
                var marketId interface{} = this.SafeString(market, "symbol")
                var baseId interface{} = this.SafeString(market, "baseCoin")
                var quoteId interface{} = this.SafeString(market, "quoteCoin")
                var base interface{} = this.SafeCurrencyCode(baseId)
                var quote interface{} = this.SafeCurrencyCode(quoteId)
                var symbol interface{} = Add(Add(base, "/"), quote)
                var active interface{} = this.SafeBool(market, "enableTrade")
                var tickSize interface{} = this.SafeString(market, "tickSize")
                var stepSize interface{} = this.SafeString(market, "stepSize")
                AppendToArray(&result,map[string]interface{} {
                    "info": market,
                    "id": marketId,
                    "symbol": symbol,
                    "base": base,
                    "quote": quote,
                    "settle": nil,
                    "baseId": baseId,
                    "quoteId": quoteId,
                    "settleId": nil,
                    "type": "spot",
                    "spot": true,
                    "margin": false,
                    "swap": false,
                    "future": false,
                    "option": false,
                    "active": active,
                    "contract": false,
                    "linear": nil,
                    "inverse": nil,
                    "contractSize": nil,
                    "expiry": nil,
                    "expiryDatetime": nil,
                    "strike": nil,
                    "optionType": nil,
                    "precision": map[string]interface{} {
                        "amount": this.ParseNumber(stepSize),
                        "price": this.ParseNumber(tickSize),
                    },
                    "limits": map[string]interface{} {
                        "leverage": map[string]interface{} {
                            "min": nil,
                            "max": nil,
                        },
                        "amount": map[string]interface{} {
                            "min": this.SafeNumber(market, "minTradeAmount"),
                            "max": this.SafeNumber(market, "maxTradeAmount"),
                        },
                        "price": map[string]interface{} {
                            "min": nil,
                            "max": nil,
                        },
                        "cost": map[string]interface{} {
                            "min": nil,
                            "max": nil,
                        },
                    },
                    "created": nil,
                })
            }
        
            ch <- result
            return nil
        
            }()
            return ch
        }
func  (this *weex) FetchTicker(symbol interface{}, optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    /**
            * @method
            * @name weex#fetchTicker
            * @description fetches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific market
            * @see https://doc-en.weex.com/#get-single-ticker
            * @param {string} symbol unified symbol of the market to fetch the ticker for
            * @param {object} [params] extra parameters specific to the exchange API endpoint
            * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/#/?id=ticker-structure}
            */
            params := GetArg(optionalArgs, 0, map[string]interface{} {})
            _ = params
        
            retRes4548 := (<-this.LoadMarkets())
            PanicOnError(retRes4548)
            var market interface{} = this.Market(symbol)
            var request interface{} = map[string]interface{} {
                "symbol": GetValue(market, "id"),
            }
        
            response:= (<-this.PublicGetMarketTicker(this.Extend(request, params)))
            PanicOnError(response)
            //
            //     {
            //       "code": "00000",
            //       "msg": "success",
            //       "requestTime": 1743665793483,
            //       "data": {
            //         "symbol": "BTCUSDT_SPBL",
            //         "priceChange": "-965.6",
            //         "priceChangePercent": "-0.011451",
            //         "trades": 105901,
            //         "size": "78570.57284800",
            //         "value": "6731333236.9492884000",
            //         "high": "88495.5",
            //         "low": "82175.9",
            //         "open": "84319.6",
            //         "close": "83354.0",
            //         "lastPrice": "83354.0",
            //         "ts": 1750060557824
            //       }
            //     }
            //
            var data interface{} = this.SafeDict(response, "data", map[string]interface{} {})
        
            ch <- this.ParseTicker(data, market)
            return nil
        
            }()
            return ch
        }
func  (this *weex) FetchTickers(optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    /**
            * @method
            * @name weex#fetchTickers
            * @description fetches price tickers for multiple markets, statistical information calculated over the past 24 hours for each market
            * @see https://doc-en.weex.com/#get-all-ticker
            * @param {string[]|undefined} symbols unified symbols of the markets to fetch the ticker for, all market tickers are returned if not assigned
            * @param {object} [params] extra parameters specific to the exchange API endpoint
            * @returns {object} a dictionary of [ticker structures]{@link https://docs.ccxt.com/#/?id=ticker-structure}
            */
            symbols := GetArg(optionalArgs, 0, nil)
            _ = symbols
            params := GetArg(optionalArgs, 1, map[string]interface{} {})
            _ = params
        
            retRes4958 := (<-this.LoadMarkets())
            PanicOnError(retRes4958)
        
            response:= (<-this.PublicGetMarketTickers(params))
            PanicOnError(response)
            //
            //     {
            //       "code": "00000",
            //       "msg": "success",
            //       "data": [
            //         {
            //           "symbol": "BTCUSDT_SPBL",
            //           "priceChange": "-965.6",
            //           "priceChangePercent": "-0.011451",
            //           // ... more ticker data
            //         }
            //       ]
            //     }
            //
            var data interface{} = this.SafeList(response, "data", []interface{}{})
            var result interface{} = map[string]interface{} {}
            for i := 0; IsLessThan(i, GetArrayLength(data)); i++ {
                var ticker interface{} = this.ParseTicker(GetValue(data, i))
                var symbol interface{} = GetValue(ticker, "symbol")
                AddElementToObject(result, symbol, ticker)
            }
        
            ch <- this.FilterByArrayTickers(result, "symbol", symbols)
            return nil
        
            }()
            return ch
        }
func  (this *weex) ParseTicker(ticker interface{}, optionalArgs ...interface{}) interface{}  {
    //
    //     {
    //       "symbol": "BTCUSDT_SPBL",
    //       "priceChange": "-965.6",
    //       "priceChangePercent": "-0.011451",
    //       "trades": 105901,
    //       "size": "78570.57284800",
    //       "value": "6731333236.9492884000",
    //       "high": "88495.5",
    //       "low": "82175.9",
    //       "open": "84319.6",
    //       "close": "83354.0",
    //       "lastPrice": "83354.0",
    //       "ts": 1750060557824
    //     }
    //
    market := GetArg(optionalArgs, 0, nil)
    _ = market
    var marketId interface{} = this.SafeString(ticker, "symbol")
    var symbol interface{} = this.SafeSymbol(marketId, market)
    var timestamp interface{} = this.SafeInteger(ticker, "ts")
    var last interface{} = this.SafeString(ticker, "lastPrice")
    var open interface{} = this.SafeString(ticker, "open")
    var high interface{} = this.SafeString(ticker, "high")
    var low interface{} = this.SafeString(ticker, "low")
    var change interface{} = this.SafeString(ticker, "priceChange")
    var percentage interface{} = this.SafeString(ticker, "priceChangePercent")
    var baseVolume interface{} = this.SafeString(ticker, "size")
    var quoteVolume interface{} = this.SafeString(ticker, "value")
    var count interface{} = this.SafeInteger(ticker, "trades")
    return this.SafeTicker(map[string]interface{} {
        "symbol": symbol,
        "timestamp": timestamp,
        "datetime": this.Iso8601(timestamp),
        "high": high,
        "low": low,
        "bid": nil,
        "bidVolume": nil,
        "ask": nil,
        "askVolume": nil,
        "vwap": nil,
        "open": open,
        "close": last,
        "last": last,
        "previousClose": nil,
        "change": change,
        "percentage": percentage,
        "average": nil,
        "baseVolume": baseVolume,
        "quoteVolume": quoteVolume,
        "count": count,
        "info": ticker,
    }, market)
}
func  (this *weex) FetchOrderBook(symbol interface{}, optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    /**
            * @method
            * @name weex#fetchOrderBook
            * @description fetches information on open orders with bid (buy) and ask (sell) prices, volumes and other data
            * @see https://doc-en.weex.com/#get-orderbook-depth
            * @param {string} symbol unified symbol of the market to fetch the order book for
            * @param {int} [limit] the maximum amount of order book entries to return (15 or 200)
            * @param {object} [params] extra parameters specific to the exchange API endpoint
            * @returns {object} A dictionary of [order book structures]{@link https://docs.ccxt.com/#/?id=order-book-structure} indexed by market symbols
            */
            limit := GetArg(optionalArgs, 0, nil)
            _ = limit
            params := GetArg(optionalArgs, 1, map[string]interface{} {})
            _ = params
        
            retRes5868 := (<-this.LoadMarkets())
            PanicOnError(retRes5868)
            var market interface{} = this.Market(symbol)
            var request interface{} = map[string]interface{} {
                "symbol": GetValue(market, "id"),
            }
            if IsTrue(!IsEqual(limit, nil)) {
                AddElementToObject(request, "limit", limit) // 15 or 200
            }
        
            response:= (<-this.PublicGetMarketDepth(this.Extend(request, params)))
            PanicOnError(response)
            //
            //     {
            //         "code":"00000",
            //         "msg":"success",
            //         "requestTime":1622102974025,
            //         "data":{
            //             "asks":[
            //                 ["38084.5","0.0039"],
            //                 ["38085.7","0.0018"]
            //             ],
            //             "bids":[
            //                 ["38073.7","0.4993000000000000"],
            //                 ["38073.4","0.4500"]
            //             ],
            //             "timestamp":"1622102974025"
            //         }
            //     }
            //
            var data interface{} = this.SafeDict(response, "data", map[string]interface{} {})
            var timestamp interface{} = this.SafeInteger(data, "timestamp")
        
            ch <- this.ParseOrderBook(data, symbol, timestamp)
            return nil
        
            }()
            return ch
        }
func  (this *weex) FetchTrades(symbol interface{}, optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    /**
            * @method
            * @name weex#fetchTrades
            * @description get the list of most recent trades for a particular symbol
            * @see https://doc-en.weex.com/#get-trades
            * @param {string} symbol unified symbol of the market to fetch trades for
            * @param {int} [since] timestamp in ms of the earliest trade to fetch
            * @param {int} [limit] the maximum amount of trades to fetch
            * @param {object} [params] extra parameters specific to the exchange API endpoint
            * @returns {Trade[]} a list of [trade structures]{@link https://docs.ccxt.com/#/?id=public-trades}
            */
            since := GetArg(optionalArgs, 0, nil)
            _ = since
            limit := GetArg(optionalArgs, 1, nil)
            _ = limit
            params := GetArg(optionalArgs, 2, map[string]interface{} {})
            _ = params
        
            retRes6308 := (<-this.LoadMarkets())
            PanicOnError(retRes6308)
            var market interface{} = this.Market(symbol)
            var request interface{} = map[string]interface{} {
                "symbol": GetValue(market, "id"),
            }
            if IsTrue(!IsEqual(limit, nil)) {
                AddElementToObject(request, "limit", limit)
            }
        
            response:= (<-this.PublicGetMarketFills(this.Extend(request, params)))
            PanicOnError(response)
            //
            //     {
            //         "code": "00000",
            //         "msg": "success",
            //         "requestTime": 1743668717640,
            //         "data": [
            //             {
            //                 "symbol": "BTCUSDT_SPBL",
            //                 "tradeId": "778a5376-a0b6-4c8f-ab64-dd6ea40f896e",
            //                 "fillTime": 1743668713364,
            //                 "fillPrice": "83609.7",
            //                 "fillQuantity": "0.00011400",
            //                 "tradeValue": "9.531505800",
            //                 "bestMatch": true,
            //                 "buyerMaker": true
            //             }
            //         ]
            //     }
            //
            var data interface{} = this.SafeList(response, "data", []interface{}{})
        
            ch <- this.ParseTrades(data, market, since, limit)
            return nil
        
            }()
            return ch
        }
func  (this *weex) ParseTrade(trade interface{}, optionalArgs ...interface{}) interface{}  {
    //
    // fetchTrades (public)
    //
    //     {
    //         "symbol": "BTCUSDT_SPBL",
    //         "tradeId": "778a5376-a0b6-4c8f-ab64-dd6ea40f896e",
    //         "fillTime": 1743668713364,
    //         "fillPrice": "83609.7",
    //         "fillQuantity": "0.00011400",
    //         "tradeValue": "9.531505800",
    //         "bestMatch": true,
    //         "buyerMaker": true
    //     }
    //
    // fetchMyTrades (private)
    //
    //     {
    //         "accountId": "590105411156181178",
    //         "symbol": "WXTUSDT_SPBL",
    //         "baseCoin": "WXT",
    //         "quoteCoin": "USDT",
    //         "orderId": "602929507946463674",
    //         "fillId": "602929507971629498",
    //         "orderType": "",
    //         "side": "buy",
    //         "fillPrice": "",
    //         "fillQuantity": "10",
    //         "fillTotalAmount": "0.10476",
    //         "fees": "0.01",
    //         "cTime": "1743749596589"
    //     }
    //
    market := GetArg(optionalArgs, 0, nil)
    _ = market
    var marketId interface{} = this.SafeString(trade, "symbol")
    var symbol interface{} = this.SafeSymbol(marketId, market)
    var id interface{} = this.SafeString2(trade, "tradeId", "fillId")
    var orderId interface{} = this.SafeString(trade, "orderId")
    var timestamp interface{} = this.SafeInteger2(trade, "fillTime", "cTime")
    var priceString interface{} = this.SafeString2(trade, "fillPrice", "fillPrice")
    var amountString interface{} = this.SafeString(trade, "fillQuantity")
    var costString interface{} = this.SafeString2(trade, "tradeValue", "fillTotalAmount")
    var side interface{} = this.SafeString(trade, "side")
    var takerOrMaker interface{} = nil
    var buyerMaker interface{} = this.SafeBool(trade, "buyerMaker")
    if IsTrue(!IsEqual(buyerMaker, nil)) {
        takerOrMaker = Ternary(IsTrue(buyerMaker), "maker", "taker")
    }
    var feeString interface{} = this.SafeString(trade, "fees")
    var fee interface{} = nil
    if IsTrue(!IsEqual(feeString, nil)) {
        fee = map[string]interface{} {
            "cost": feeString,
            "currency": nil,
        }
    }
    return this.SafeTrade(map[string]interface{} {
        "info": trade,
        "id": id,
        "order": orderId,
        "timestamp": timestamp,
        "datetime": this.Iso8601(timestamp),
        "symbol": symbol,
        "type": nil,
        "side": side,
        "amount": amountString,
        "price": priceString,
        "cost": costString,
        "takerOrMaker": takerOrMaker,
        "fee": fee,
    }, market)
}
func  (this *weex) FetchOHLCV(symbol interface{}, optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    /**
            * @method
            * @name weex#fetchOHLCV
            * @description fetches historical candlestick data containing the open, high, low, and close price, and the volume of a market
            * @see https://doc-en.weex.com/#get-candlestick-data
            * @param {string} symbol unified symbol of the market to fetch OHLCV data for
            * @param {string} timeframe the length of time each candle represents
            * @param {int} [since] timestamp in ms of the earliest candle to fetch
            * @param {int} [limit] the maximum amount of candles to fetch
            * @param {object} [params] extra parameters specific to the exchange API endpoint
            * @returns {int[][]} A list of candles ordered as timestamp, open, high, low, close, volume
            */
            timeframe := GetArg(optionalArgs, 0, "1m")
            _ = timeframe
            since := GetArg(optionalArgs, 1, nil)
            _ = since
            limit := GetArg(optionalArgs, 2, nil)
            _ = limit
            params := GetArg(optionalArgs, 3, map[string]interface{} {})
            _ = params
        
            retRes7478 := (<-this.LoadMarkets())
            PanicOnError(retRes7478)
            var market interface{} = this.Market(symbol)
            var request interface{} = map[string]interface{} {
                "symbol": GetValue(market, "id"),
                "period": this.SafeString(this.Timeframes, timeframe, timeframe),
            }
            if IsTrue(!IsEqual(limit, nil)) {
                AddElementToObject(request, "limit", limit)
            }
        
            response:= (<-this.PublicGetMarketCandles(this.Extend(request, params)))
            PanicOnError(response)
            //
            //     {
            //       "code": "00000",
            //       "msg": "success",
            //       "requestTime": 1743669821003,
            //       "data": [
            //         [
            //           1743669000000,
            //           "83654.0",
            //           "83778.0",
            //           "83531.5",
            //           "83688.7",
            //           "248.17024800",
            //           "20755885.859164900"
            //         ]
            //       ]
            //     }
            //
            var data interface{} = this.SafeList(response, "data", []interface{}{})
        
            ch <- this.ParseOHLCVs(data, market, timeframe, since, limit)
            return nil
        
            }()
            return ch
        }
func  (this *weex) ParseOHLCV(ohlcv interface{}, optionalArgs ...interface{}) interface{}  {
    //
    //     [
    //       1743669000000,
    //       "83654.0",
    //       "83778.0",
    //       "83531.5",
    //       "83688.7",
    //       "248.17024800",
    //       "20755885.859164900"
    //     ]
    //
    market := GetArg(optionalArgs, 0, nil)
    _ = market
    return []interface{}{this.SafeInteger(ohlcv, 0), this.SafeNumber(ohlcv, 1), this.SafeNumber(ohlcv, 2), this.SafeNumber(ohlcv, 3), this.SafeNumber(ohlcv, 4), this.SafeNumber(ohlcv, 5)}
}
func  (this *weex) FetchBalance(optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    /**
            * @method
            * @name weex#fetchBalance
            * @description query for balance and get the amount of funds available for trading or funds locked in orders
            * @see https://doc-en.weex.com/#get-account-assets
            * @param {object} [params] extra parameters specific to the exchange API endpoint
            * @returns {object} a [balance structure]{@link https://docs.ccxt.com/#/?id=balance-structure}
            */
            params := GetArg(optionalArgs, 0, map[string]interface{} {})
            _ = params
        
            retRes8108 := (<-this.LoadMarkets())
            PanicOnError(retRes8108)
        
            response:= (<-this.PrivateGetAccountAssets(params))
            PanicOnError(response)
            //
            //     {
            //       "code": "00000",
            //       "msg": "success",
            //       "requestTime": 1743729400189,
            //       "data": [{
            //         "coinId": 1,
            //         "coinName": "BTC",
            //         "available": "0.0040000000000000",
            //         "frozen": "0",
            //         "equity": "0.0040000000000000"
            //       }, {
            //         "coinId": 2,
            //         "coinName": "USDT",
            //         "available": "10000999657.8927028500000000",
            //         "frozen": "0",
            //         "equity": "10000999657.8927028500000000"
            //       }]
            //     }
            //
            var data interface{} = this.SafeList(response, "data", []interface{}{})
        
            ch <- this.ParseBalance(data)
            return nil
        
            }()
            return ch
        }
func  (this *weex) ParseBalance(response interface{}) interface{}  {
    var result interface{} = map[string]interface{} {
        "info": response,
        "timestamp": nil,
        "datetime": nil,
    }
    for i := 0; IsLessThan(i, GetArrayLength(response)); i++ {
        var balance interface{} = GetValue(response, i)
        var currencyId interface{} = this.SafeString(balance, "coinName")
        var code interface{} = this.SafeCurrencyCode(currencyId)
        var account interface{} = this.Account()
        AddElementToObject(account, "free", this.SafeString(balance, "available"))
        AddElementToObject(account, "used", this.SafeString(balance, "frozen"))
        AddElementToObject(account, "total", this.SafeString(balance, "equity"))
        AddElementToObject(result, code, account)
    }
    return this.SafeBalance(result)
}
func  (this *weex) CreateOrder(symbol interface{}, typeVar interface{}, side interface{}, amount interface{}, optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    /**
            * @method
            * @name weex#createOrder
            * @description create a trade order
            * @see https://doc-en.weex.com/#place-order
            * @param {string} symbol unified symbol of the market to create an order in
            * @param {string} type 'market' or 'limit'
            * @param {string} side 'buy' or 'sell'
            * @param {float} amount how much of currency you want to trade in units of base currency
            * @param {float} [price] the price at which the order is to be fulfilled, in units of the quote currency, ignored in market orders
            * @param {object} [params] extra parameters specific to the exchange API endpoint
            * @param {string} [params.clientOrderId] client order id, defaults to uuid if not passed
            * @param {string} [params.force] order execution type: 'normal', 'postOnly', 'fok', 'ioc'
            * @returns {object} an [order structure]{@link https://docs.ccxt.com/#/?id=order-structure}
            */
            price := GetArg(optionalArgs, 0, nil)
            _ = price
            params := GetArg(optionalArgs, 1, map[string]interface{} {})
            _ = params
        
            retRes8718 := (<-this.LoadMarkets())
            PanicOnError(retRes8718)
            var market interface{} = this.Market(symbol)
            var request interface{} = map[string]interface{} {
                "symbol": GetValue(market, "id"),
                "side": side,
                "orderType": typeVar,
                "quantity": this.AmountToPrecision(symbol, amount),
            }
            var clientOrderId interface{} = this.SafeString(params, "clientOrderId", this.Uuid())
            AddElementToObject(request, "clientOrderId", clientOrderId)
            if IsTrue(IsEqual(typeVar, "limit")) {
                if IsTrue(IsEqual(price, nil)) {
                    panic(ArgumentsRequired(Add(this.Id, " createOrder() requires a price argument for limit orders")))
                }
                AddElementToObject(request, "price", this.PriceToPrecision(symbol, price))
            }
            var force interface{} = this.SafeString(params, "force", "normal")
            AddElementToObject(request, "force", force)
            params = this.Omit(params, []interface{}{"clientOrderId", "force"})
        
            response:= (<-this.PrivatePostTradeOrders(this.Extend(request, params)))
            PanicOnError(response)
            //
            //     {
            //       "code": "00000",
            //       "msg": "success",
            //       "requestTime": 1743736915184,
            //       "data": {
            //         "orderId": 602876318261969338,
            //         "clientOrderId": "202504041121509751743736910566"
            //       }
            //     }
            //
            var data interface{} = this.SafeDict(response, "data", map[string]interface{} {})
        
            ch <- this.ParseOrder(data, market)
            return nil
        
            }()
            return ch
        }
func  (this *weex) CancelOrder(id interface{}, optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    /**
            * @method
            * @name weex#cancelOrder
            * @description cancels an open order
            * @see https://doc-en.weex.com/#cancel-order
            * @param {string} id order id
            * @param {string} symbol unified symbol of the market the order was made in
            * @param {object} [params] extra parameters specific to the exchange API endpoint
            * @param {string} [params.clientOrderId] client order id
            * @returns {object} An [order structure]{@link https://docs.ccxt.com/#/?id=order-structure}
            */
            symbol := GetArg(optionalArgs, 0, nil)
            _ = symbol
            params := GetArg(optionalArgs, 1, map[string]interface{} {})
            _ = params
            if IsTrue(IsEqual(symbol, nil)) {
                panic(ArgumentsRequired(Add(this.Id, " cancelOrder() requires a symbol argument")))
            }
        
            retRes9218 := (<-this.LoadMarkets())
            PanicOnError(retRes9218)
            var market interface{} = this.Market(symbol)
            var request interface{} = map[string]interface{} {
                "symbol": GetValue(market, "id"),
            }
            var clientOrderId interface{} = this.SafeString(params, "clientOrderId")
            if IsTrue(!IsEqual(clientOrderId, nil)) {
                AddElementToObject(request, "clientOid", clientOrderId)
            } else {
                AddElementToObject(request, "orderId", id)
            }
            params = this.Omit(params, []interface{}{"clientOrderId"})
        
            response:= (<-this.PrivatePostTradeCancelOrder(this.Extend(request, params)))
            PanicOnError(response)
            //
            //     {
            //       "code": "00000",
            //       "msg": "success",
            //       "requestTime": 1743740792018,
            //       "data": {
            //         "order_id": "602882076026339770",
            //         "client_oid": null,
            //         "symbol": "WXTUSDT_SPBL",
            //         "result": true,
            //         "err_code": null,
            //         "err_msg": null
            //       }
            //     }
            //
            var data interface{} = this.SafeDict(response, "data", map[string]interface{} {})
        
            ch <- this.ParseOrder(data, market)
            return nil
        
            }()
            return ch
        }
func  (this *weex) FetchOrder(id interface{}, optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    /**
            * @method
            * @name weex#fetchOrder
            * @description fetches information on an order made by the user
            * @see https://doc-en.weex.com/#get-order-info
            * @param {string} id the order id
            * @param {string} symbol unified symbol of the market the order was made in
            * @param {object} [params] extra parameters specific to the exchange API endpoint
            * @param {string} [params.clientOrderId] client order id
            * @returns {object} An [order structure]{@link https://docs.ccxt.com/#/?id=order-structure}
            */
            symbol := GetArg(optionalArgs, 0, nil)
            _ = symbol
            params := GetArg(optionalArgs, 1, map[string]interface{} {})
            _ = params
        
            retRes9658 := (<-this.LoadMarkets())
            PanicOnError(retRes9658)
            var market interface{} = this.Market(symbol)
            var request interface{} = map[string]interface{} {}
            var clientOrderId interface{} = this.SafeString(params, "clientOrderId")
            if IsTrue(!IsEqual(clientOrderId, nil)) {
                AddElementToObject(request, "clientOrderId", clientOrderId)
            } else {
                AddElementToObject(request, "orderId", id)
            }
            params = this.Omit(params, []interface{}{"clientOrderId"})
        
            response:= (<-this.PrivatePostTradeOrderInfo(this.Extend(request, params)))
            PanicOnError(response)
            //
            //     {
            //       "code": "00000",
            //       "msg": "success",
            //       "requestTime": 1743754256238,
            //       "data": [{
            //         "accountId": "590105411156181178",
            //         "symbol": "WXTUSDT_SPBL",
            //         "orderId": "602928955330134458",
            //         "clientOrderId": "202504041451014391743749461316",
            //         "price": "100.000000",
            //         "quantity": "10",
            //         "orderType": "limit",
            //         "side": "sell",
            //         "status": "open",
            //         "latestFillPrice": "0",
            //         "maxFillPrice": "0",
            //         "minFillPrice": "0",
            //         "fillQuantity": "0",
            //         "fillTotalAmount": "0",
            //         "cTime": "1743749464829",
            //         "uTime": "1743749464834"
            //       }]
            //     }
            //
            var data interface{} = this.SafeList(response, "data", []interface{}{})
            var first interface{} = this.SafeDict(data, 0, map[string]interface{} {})
        
            ch <- this.ParseOrder(first, market)
            return nil
        
            }()
            return ch
        }
func  (this *weex) ParseOrder(order interface{}, optionalArgs ...interface{}) interface{}  {
    //
    // createOrder
    //
    //     {
    //       "orderId": 602876318261969338,
    //       "clientOrderId": "202504041121509751743736910566"
    //     }
    //
    // cancelOrder
    //
    //     {
    //       "order_id": "602882076026339770",
    //       "client_oid": null,
    //       "symbol": "WXTUSDT_SPBL",
    //       "result": true,
    //       "err_code": null,
    //       "err_msg": null
    //     }
    //
    // fetchOrder, fetchOrders, fetchOpenOrders
    //
    //     {
    //       "accountId": "590105411156181178",
    //       "symbol": "WXTUSDT_SPBL",
    //       "orderId": "602928955330134458",
    //       "clientOrderId": "202504041451014391743749461316",
    //       "price": "100.000000",
    //       "quantity": "10",
    //       "orderType": "limit",
    //       "side": "sell",
    //       "status": "open",
    //       "latestFillPrice": "0",
    //       "maxFillPrice": "0",
    //       "minFillPrice": "0",
    //       "fillQuantity": "0",
    //       "fillTotalAmount": "0",
    //       "cTime": "1743749464829",
    //       "uTime": "1743749464834"
    //     }
    //
    market := GetArg(optionalArgs, 0, nil)
    _ = market
    var marketId interface{} = this.SafeString(order, "symbol")
    var symbol interface{} = this.SafeSymbol(marketId, market)
    var id interface{} = this.SafeString2(order, "orderId", "order_id")
    var clientOrderId interface{} = this.SafeString2(order, "clientOrderId", "client_oid")
    var timestamp interface{} = this.SafeInteger(order, "cTime")
    var lastUpdateTimestamp interface{} = this.SafeInteger(order, "uTime")
    var typeVar interface{} = this.SafeString(order, "orderType")
    var side interface{} = this.SafeString(order, "side")
    var amount interface{} = this.SafeString(order, "quantity")
    var price interface{} = this.SafeString(order, "price")
    var filled interface{} = this.SafeString(order, "fillQuantity")
    var cost interface{} = this.SafeString(order, "fillTotalAmount")
    var average interface{} = this.SafeString(order, "latestFillPrice")
    var status interface{} = this.SafeString(order, "status")
    if IsTrue(IsEqual(status, "new")) {
        status = "open"
    } else if IsTrue(IsEqual(status, "partial_fill")) {
        status = "open"
    } else if IsTrue(IsEqual(status, "full_fill")) {
        status = "closed"
    } else if IsTrue(IsEqual(status, "cancelled")) {
        status = "canceled"
    }
    return this.SafeOrder(map[string]interface{} {
        "info": order,
        "id": id,
        "clientOrderId": clientOrderId,
        "timestamp": timestamp,
        "datetime": this.Iso8601(timestamp),
        "lastTradeTimestamp": lastUpdateTimestamp,
        "lastUpdateTimestamp": lastUpdateTimestamp,
        "symbol": symbol,
        "type": typeVar,
        "timeInForce": nil,
        "postOnly": nil,
        "side": side,
        "amount": amount,
        "price": price,
        "stopPrice": nil,
        "triggerPrice": nil,
        "cost": cost,
        "average": average,
        "filled": filled,
        "remaining": nil,
        "status": status,
        "fee": nil,
        "trades": nil,
    }, market)
}
func  (this *weex) FetchOpenOrders(optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    /**
            * @method
            * @name weex#fetchOpenOrders
            * @description fetch all unfilled currently open orders
            * @see https://doc-en.weex.com/#get-current-orders
            * @param {string} symbol unified market symbol
            * @param {int} [since] the earliest time in ms to fetch open orders for
            * @param {int} [limit] the maximum number of  open orders structures to retrieve
            * @param {object} [params] extra parameters specific to the exchange API endpoint
            * @param {int} [params.pageNo] page number (starting from 0, default 0)
            * @returns {Order[]} a list of [order structures]{@link https://docs.ccxt.com/#/?id=order-structure}
            */
            symbol := GetArg(optionalArgs, 0, nil)
            _ = symbol
            since := GetArg(optionalArgs, 1, nil)
            _ = since
            limit := GetArg(optionalArgs, 2, nil)
            _ = limit
            params := GetArg(optionalArgs, 3, map[string]interface{} {})
            _ = params
            if IsTrue(IsEqual(symbol, nil)) {
                panic(ArgumentsRequired(Add(this.Id, " fetchOpenOrders() requires a symbol argument")))
            }
        
            retRes11138 := (<-this.LoadMarkets())
            PanicOnError(retRes11138)
            var market interface{} = this.Market(symbol)
            var request interface{} = map[string]interface{} {
                "symbol": GetValue(market, "id"),
            }
            if IsTrue(!IsEqual(limit, nil)) {
                AddElementToObject(request, "limit", limit)
            }
            var pageNo interface{} = this.SafeInteger(params, "pageNo")
            if IsTrue(!IsEqual(pageNo, nil)) {
                AddElementToObject(request, "pageNo", pageNo)
            }
            params = this.Omit(params, []interface{}{"pageNo"})
        
            response:= (<-this.PrivatePostTradeOpenOrders(this.Extend(request, params)))
            PanicOnError(response)
            //
            //     {
            //       "code": "00000",
            //       "msg": "success",
            //       "requestTime": 1743753174247,
            //       "data": {
            //         "orderInfoResultList": [{
            //           "accountId": "590105411156181178",
            //           "symbol": "WXTUSDT_SPBL",
            //           "orderId": "602941812964852154",
            //           "clientOrderId": "202504040742105191743752530280",
            //           // ... more order data
            //         }],
            //         "nextPage": null,
            //         "totals": null
            //       }
            //     }
            //
            var data interface{} = this.SafeDict(response, "data", map[string]interface{} {})
            var orders interface{} = this.SafeList(data, "orderInfoResultList", []interface{}{})
        
            ch <- this.ParseOrders(orders, market, since, limit)
            return nil
        
            }()
            return ch
        }
func  (this *weex) FetchOrders(optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    /**
            * @method
            * @name weex#fetchOrders
            * @description fetches information on multiple orders made by the user
            * @see https://doc-en.weex.com/#get-history-orders
            * @param {string} symbol unified market symbol of the market orders were made in
            * @param {int} [since] the earliest time in ms to fetch orders for
            * @param {int} [limit] the maximum number of order structures to retrieve
            * @param {object} [params] extra parameters specific to the exchange API endpoint
            * @param {int} [params.after] start timestamp (in milliseconds)
            * @param {int} [params.before] end timestamp (in milliseconds)
            * @param {int} [params.pageIndex] page number, starting from 0 (Default: 0)
            * @param {int} [params.pageSize] page size, must be greater than 0 and less than or equal to 100 (Default: 10)
            * @returns {Order[]} a list of [order structures]{@link https://docs.ccxt.com/#/?id=order-structure}
            */
            symbol := GetArg(optionalArgs, 0, nil)
            _ = symbol
            since := GetArg(optionalArgs, 1, nil)
            _ = since
            limit := GetArg(optionalArgs, 2, nil)
            _ = limit
            params := GetArg(optionalArgs, 3, map[string]interface{} {})
            _ = params
            if IsTrue(IsEqual(symbol, nil)) {
                panic(ArgumentsRequired(Add(this.Id, " fetchOrders() requires a symbol argument")))
            }
        
            retRes11698 := (<-this.LoadMarkets())
            PanicOnError(retRes11698)
            var market interface{} = this.Market(symbol)
            var request interface{} = map[string]interface{} {
                "symbol": GetValue(market, "id"),
            }
            if IsTrue(!IsEqual(since, nil)) {
                AddElementToObject(request, "after", since)
            }
            if IsTrue(!IsEqual(limit, nil)) {
                AddElementToObject(request, "pageSize", limit)
            }
        
            response:= (<-this.PrivatePostTradeHistory(this.Extend(request, params)))
            PanicOnError(response)
            //
            //     {
            //       "code": "00000",
            //       "msg": "success",
            //       "requestTime": 1743755234949,
            //       "data": {
            //         "orderInfoResultList": [{
            //           "accountId": "590105411156181178",
            //           "symbol": "WXTUSDT_SPBL",
            //           "orderId": "602941812964852154",
            //           // ... more order data
            //         }],
            //         "nextPage": true,
            //         "totals": 0
            //       }
            //     }
            //
            var data interface{} = this.SafeDict(response, "data", map[string]interface{} {})
            var orders interface{} = this.SafeList(data, "orderInfoResultList", []interface{}{})
        
            ch <- this.ParseOrders(orders, market, since, limit)
            return nil
        
            }()
            return ch
        }
func  (this *weex) FetchMyTrades(optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    /**
            * @method
            * @name weex#fetchMyTrades
            * @description fetch all trades made by the user
            * @see https://doc-en.weex.com/#get-fills
            * @param {string} symbol unified market symbol
            * @param {int} [since] the earliest time in ms to fetch trades for
            * @param {int} [limit] the maximum number of trades structures to retrieve
            * @param {object} [params] extra parameters specific to the exchange API endpoint
            * @param {string} [params.orderId] order id
            * @param {int} [params.after] start timestamp (in milliseconds)
            * @param {int} [params.before] end timestamp (in milliseconds)
            * @param {int} [params.pageIndex] page number, starting from 0 (Default: 0)
            * @param {int} [params.pageSize] page size, must be greater than 0 and less than or equal to 100 (Default: 10)
            * @returns {Trade[]} a list of [trade structures]{@link https://docs.ccxt.com/#/?id=trade-structure}
            */
            symbol := GetArg(optionalArgs, 0, nil)
            _ = symbol
            since := GetArg(optionalArgs, 1, nil)
            _ = since
            limit := GetArg(optionalArgs, 2, nil)
            _ = limit
            params := GetArg(optionalArgs, 3, map[string]interface{} {})
            _ = params
            if IsTrue(IsEqual(symbol, nil)) {
                panic(ArgumentsRequired(Add(this.Id, " fetchMyTrades() requires a symbol argument")))
            }
        
            retRes12238 := (<-this.LoadMarkets())
            PanicOnError(retRes12238)
            var market interface{} = this.Market(symbol)
            var request interface{} = map[string]interface{} {
                "symbol": GetValue(market, "id"),
            }
            if IsTrue(!IsEqual(since, nil)) {
                AddElementToObject(request, "after", since)
            }
            if IsTrue(!IsEqual(limit, nil)) {
                AddElementToObject(request, "pageSize", limit)
            }
        
            response:= (<-this.PrivatePostTradeFills(this.Extend(request, params)))
            PanicOnError(response)
            //
            //     {
            //       "code": "00000",
            //       "msg": "success",
            //       "requestTime": 1743750228305,
            //       "data": {
            //         "fillsOrderResultList": [{
            //           "accountId": "590105411156181178",
            //           "symbol": "WXTUSDT_SPBL",
            //           "baseCoin": "WXT",
            //           "quoteCoin": "USDT",
            //           "orderId": "602929507946463674",
            //           "fillId": "602929507971629498",
            //           "orderType": "",
            //           "side": "buy",
            //           "fillPrice": "",
            //           "fillQuantity": "10",
            //           "fillTotalAmount": "0.10476",
            //           "fees": "0.01",
            //           "cTime": "1743749596589"
            //         }],
            //         "nextPage": false,
            //         "totals": 0
            //       }
            //     }
            //
            var data interface{} = this.SafeDict(response, "data", map[string]interface{} {})
            var trades interface{} = this.SafeList(data, "fillsOrderResultList", []interface{}{})
        
            ch <- this.ParseTrades(trades, market, since, limit)
            return nil
        
            }()
            return ch
        }
func  (this *weex) Sign(path interface{}, optionalArgs ...interface{}) interface{}  {
    api := GetArg(optionalArgs, 0, "public")
    _ = api
    method := GetArg(optionalArgs, 1, "GET")
    _ = method
    params := GetArg(optionalArgs, 2, map[string]interface{} {})
    _ = params
    headers := GetArg(optionalArgs, 3, nil)
    _ = headers
    body := GetArg(optionalArgs, 4, nil)
    _ = body
    var url interface{} = Add(Add(GetValue(GetValue(this.Urls, "api"), api), "/"), path)
    if IsTrue(IsEqual(api, "public")) {
        if IsTrue(GetArrayLength(ObjectKeys(params))) {
            url = Add(url, Add("?", this.Urlencode(params)))
        }
    } else if IsTrue(IsEqual(api, "private")) {
        this.CheckRequiredCredentials()
        var timestamp interface{} = ToString(this.Milliseconds())
        var queryString interface{} = ""
        if IsTrue(IsEqual(method, "GET")) {
            if IsTrue(GetArrayLength(ObjectKeys(params))) {
                queryString = Add("?", this.Urlencode(params))
                url = Add(url, queryString)
            }
        } else {
            if IsTrue(GetArrayLength(ObjectKeys(params))) {
                body = this.Json(params)
            }
        }
        var auth interface{} = Add(Add(Add(timestamp, ToUpper(method)), "/"), path)
        var message interface{} = Add(Add(auth, queryString), (IsTrue(body) || IsTrue("")))
        var signature interface{} = this.Hmac(this.Encode(message), this.Encode(this.Secret), sha256, "base64")
        headers = map[string]interface{} {
            "ACCESS-KEY": this.ApiKey,
            "ACCESS-SIGN": signature,
            "ACCESS-TIMESTAMP": timestamp,
            "ACCESS-PASSPHRASE": this.Password,
            "Content-Type": "application/json",
            "locale": "en-US",
        }
    }
    return map[string]interface{} {
        "url": url,
        "method": method,
        "body": body,
        "headers": headers,
    }
}
func  (this *weex) HandleErrors(httpCode interface{}, reason interface{}, url interface{}, method interface{}, headers interface{}, body interface{}, response interface{}, requestHeaders interface{}, requestBody interface{})  {
    if IsTrue(IsEqual(response, nil)) {
        return  // fallback to default error handler
    }
    //
    //     {
    //         "code": "40001",
    //         "msg": "Header \"ACCESS_KEY\" is required",
    //         "requestTime": 1622097118135
    //     }
    //
    var code interface{} = this.SafeString(response, "code")
    var message interface{} = this.SafeString(response, "msg")
    if IsTrue(IsTrue(!IsEqual(code, nil)) && IsTrue(!IsEqual(code, "00000"))) {
        var feedback interface{} = Add(Add(this.Id, " "), body)
        this.ThrowExactlyMatchedException(GetValue(this.Exceptions, "exact"), code, feedback)
        this.ThrowBroadlyMatchedException(GetValue(this.Exceptions, "broad"), message, feedback)
        panic(ExchangeError(feedback))
    }
}


func (this *weex) Init(userConfig map[string]interface{}) {
    this.Exchange = Exchange{}
    this.Exchange.DerivedExchange = this
    this.Exchange.InitParent(userConfig, this.Describe().(map[string]interface{}), this)
}
